// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Sun Sep 22 21:10:25 2019
`timescale 1ns/1ps

module barrel_tb;


reg [2:0] bs_opsel_sig;
reg [4:0] shift_amount_sig;
reg [31:0] data_in_sig;
wire [31:0] result_sig;

integer i, j;

barrel barrel_inst
(
	.bs_opsel(bs_opsel_sig) ,	// input [2:0] bs_opsel_sig
	.shift_amount(shift_amount_sig) ,	// input [4:0] shift_amount_sig
	.data_in(data_in_sig) ,	// input [31:0] data_in_sig
	.result(result_sig) 	// output [31:0] result_sig
);

initial begin

	shift_amount_sig = 0;
	bs_opsel_sig = 0;
	data_in_sig = $random;
	
	for(i = 0; i <= 16; i = i + 4) begin
		shift_amount_sig = i;
	
		for(j = 0; j <= 7; j = j + 1) begin
			bs_opsel_sig = j;
			#2;
		end
	end

	shift_amount_sig = 0;
	bs_opsel_sig = 0;
	data_in_sig = 0;
	

end


initial begin
	#100 $stop();
end

endmodule
