// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Sat Sep 14 17:08:21 2019
`timescale 1ns/1ps

module demux_tb;

reg [4:0] i_ADDR_sig;
reg i_I_sig;
wire [31:0] o_O_sig;

demux_ver demux_ver_inst
(
	.i_ADDR(i_ADDR_sig) ,	// input [4:0] i_ADDR_sig
	.i_I(i_I_sig) ,	// input  i_I_sig
	.o_O(o_O_sig) 	// output [31:0] o_O_sig
);

initial begin
	i_I_sig = 1'b1;
end

initial begin
	i_ADDR_sig = 4'b0000;
	
	forever #1 i_ADDR_sig = i_ADDR_sig + 1;
end

initial begin
	#100 $stop();
end

endmodule

