`timescale 1ns/1ps
// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Fri Sep 27 14:08:26 2019

module lab3_barrel_shifter_inst;

reg [2:0] bs_opsel_sig;
reg [4:0] shift_amount_sig;
reg [31:0] data_in_sig;
wire [31:0] result_sig;



lab3_barrel_shifter lab3_barrel_shifter_inst
(
	.bs_opsel(bs_opsel_sig) ,	// input [2:0] bs_opsel_sig
	.shift_amount(shift_amount_sig) ,	// input [4:0] shift_amount_sig
	.data_in(data_in_sig) ,	// input [31:0] data_in_sig
	.result(result_sig) 	// output [31:0] result_sig
);

initial begin 
	data_in_sig= 32'h12345678;
	bs_opsel_sig = 3'b000;
	shift_amount_sig = 5'h4;

	//for (int i = 0; i < 8; i++) begin  //***all code part taken from Vadim harchuk
	//	#10 bs_opsel_sig = 3'(i);
//	end
	#10 bs_opsel_sig = 3'b000;
	#10 bs_opsel_sig = 3'b001;
	#10 bs_opsel_sig = 3'b010;
	#10 bs_opsel_sig = 3'b011;
	#10 bs_opsel_sig = 3'b111;
	
end

initial begin
	#100 $stop();
end


endmodule
