// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Sun Oct  6 17:03:02 2019
`timescale 1ns/1ps

module mips_core_tb();

reg clk_sig;
reg arst_n_sig;

wire [2:0] LEDR_sig;
wire [6:0] instr_sig;

mips_core mips_core_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.arst_n(arst_n_sig) ,	// input  arst_n_sig
	.LEDR(LEDR_sig) ,
	.instr(instr_sig)
);

initial begin
	clk_sig = 0;
	forever #2 clk_sig = ~clk_sig;
end

initial begin
	arst_n_sig = 0;
	#3 arst_n_sig = 1;
end

initial begin
	#500 $stop();
end

endmodule

