
// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Wed Oct 23 03:45:11 2019

`timescale 1ns/1ps

module lab4_alu_inst;

reg  [31:0] in_A_sig ; // взяв у Назара Волинка
reg  [31:0] in_B_sig ;
reg  [4:0] in_func_sig;
wire [31:0] out_result_sig;
wire out_overlow_sig, out_zero_sig;
reg [4:0] shamt_sig;


lab4_alu lab4_alu_inst
(
	.in_A(in_A_sig) ,	// input [31:0] in_A_sig
	.in_B(in_B_sig) ,	// input [31:0] in_B_sig
	.in_func(in_func_sig) ,	// input [4:0] in_func_sig
	.out_result(out_result_sig) ,	// output [31:0] out_result_sig
	.out_overflow(out_overflow_sig) ,	// output  out_overflow_sig
	.out_zero(out_zero_sig) ,	// output  out_zero_sig
	.shamt(shamt_sig) 	// input [4:0] shamt_sig
);



initial begin 

	in_A_sig= 32'habcdabcd;
	in_B_sig= 32'habcdabcd;

	in_func_sig = 5'b00000;     //SLL  
	#10 in_func_sig = 5'b00010; //SRL 
	#10 in_func_sig = 5'b00001; //ROL
	#10 in_func_sig = 5'b00011; //ROR
	#10 in_func_sig = 5'b00110; //SRA

	#10 in_func_sig = 5'b10000; //MUL LOW part (779D 8229)
	#10 in_func_sig = 5'b10010; //MUL HIGH part (734C 68C0)
	#10 in_func_sig = 5'b10001; //DIV result (0000 0001)
	#10 in_func_sig = 5'b10011; //DIV remaind (0000 0000)
	// ABCD ABCD * ABCD ABCD = 734C 68C0 779D 8229
	// ABCD ABCD / ABCD ABCD = 0000 0001 (remaind 0)

	#10 in_A_sig= 32'h22222222;
	in_B_sig= 32'h44444444;
	in_func_sig = 5'b10110;     //ADD
	#10 in_func_sig = 5'b10111; //SUB
	//2222 2222 + 4444 4444 = 6666 6666
	//2222 2222 - 4444 4444 = EEEE EEEE

	#10 in_A_sig= 32'h11111111;
	in_B_sig= 32'h00000000;
	in_func_sig = 5'b11000;     //AND
	#10 in_func_sig = 5'b11001; //OR
	#10 in_func_sig = 5'b11010; //NOR
	#10 in_func_sig = 5'b11011; //XOR
	#10;in_func_sig = 5'b11111; //SLT

end

initial begin 
	#500 $stop();
end

endmodule
