
// Generated by Quartus II 32-bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Wed Sep 25 02:32:36 2019
`timescale 1ns/1ps

module Lab2_RegFile;

reg clk_sig;
reg we_sig;
reg arstn_sig;
reg [4:0] in_write_sig;
reg [4:0] addreader_a_sig;
reg [4:0] addreader_b_sig;
reg [31:0] data_in_sig;
wire [31:0] out_a_sig;
wire [31:0] out_b_sig;

integer i = 0;

RegFile_Lab2 RegFile_Lab2_inst
(
	.we(we_sig) ,	// input  we_sig
	.clk(clk_sig) ,	// input  clk_sig
	.arstn(arstn_sig) ,	// input  arstn_sig
	.in_write(in_write_sig) ,	// input [4:0] in_write_sig
	.addreader_a(addreader_a_sig) ,	// input [4:0] addreader_a_sig
	.addreader_b(addreader_b_sig) ,	// input [4:0] addreader_b_sig
	.data_in(data_in_sig) ,	// input [31:0] data_in_sig
	.out_a(out_a_sig) ,	// output [31:0] out_a_sig
	.out_b(out_b_sig) 	// output [31:0] out_b_sig
);

initial begin

	clk_sig = 1'b0;
	forever #1 clk_sig = ~clk_sig;

end

initial begin

	arstn_sig = 1'b1;
	#5 arstn_sig = 1'b0;
	#7 arstn_sig = 1'b1;

end

initial begin

	we_sig = 1'b1;

end

initial begin

	addreader_a_sig = 1'b0;
	addreader_b_sig = 1'b0;

end

initial begin 
	
	in_write_sig = 0;

	for(i = 0; i < 32; i = i + 1) begin
		
		#2 in_write_sig = i;
		#5 data_in_sig = i;
		#3 addreader_a_sig = i;
		#3 addreader_b_sig = i;

	end
end

initial begin 

	#450 $stop();

end

endmodule


