

// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Tue Nov  5 21:22:13 2019
`timescale 1ns/1ps

module Block1_inst;

reg clk_sig;
reg arst_sig;
wire ovrflow_sig;





Block1 Block1_inst
(
	.arst(arst_sig) ,	// input  arst_sig
	.clk(clk_sig) ,	// input  clk_sig
	.ovrflow(ovrflow_sig) 	// output  ovrflow_sig
);

initial begin
	clk_sig = 0;
	forever #1 clk_sig = ~clk_sig;
end


initial begin
	arst_sig = 0;
	#3 arst_sig = 1;
end

initial begin
	#1000 $stop();
end

endmodule
