`timescale 1ns / 1ps

// Generated by Quartus II 32-bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Tue Oct  1 16:20:52 2019

module barrel_shifter_inst;

wire [31:0] result_sig;
reg [31:0] data_in_sig;
reg [2:0] bs_opsel_sig;
reg [4:0] shift_amount_sig;

barrel_shifter barrel_shifter_inst
(
	.data_in(data_in_sig),			// input [31:0] data_in_sig
	.bs_opsel(bs_opsel_sig),		// input [2:0] bs_opsel_sig
	.shift_amount(shift_amount_sig),	// input [4:0] shift_amount_sig
	.result(result_sig) 			// output [31:0] result_sig
);

initial begin 
	
	data_in_sig = 32'h14881488;
	bs_opsel_sig = 3'b000;
	shift_amount_sig = 5'h4;

	#5 bs_opsel_sig = 3'b000;	// Simple and genious idea was taken 	
	#5 bs_opsel_sig = 3'b001;	// from Kharchuk Vadim, student of DK-72 group
	#5 bs_opsel_sig = 3'b010;
	#5 bs_opsel_sig = 3'b011;
	#5 bs_opsel_sig = 3'b111;
 
end

initial begin

	#50 $stop();

end

endmodule

