
`timescale 1ns/1ps

// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Sat Sep 14 17:51:44 2019
module lab1_tb;

reg clk_sig;
reg arst_sig;
reg we_sig;
reg rst_sig;
reg data_sig;
reg q_sig;

lab1 lab1_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.arst(arst_sig) ,	// input  arst_sig
	.we(we_sig) ,	// input  we_sig
	.rst(rst_sig) ,	// input  rst_sig
	.data(data_sig) ,	// input [31:0] data_sig
	.q(q_sig) 	// output [31:0] q_sig
);

initial begin
	clk_sig = 1'b0;
	forever #1 clk_sig =~clk_sig;
end

initial begin
	arst_sig = 1'b1;
	we_sig = 1'b1;
	rst_sig = 1'b0;
	data_sig = 32'h12345678;
	q_sig = 32'h00000000;

	#2 arst_sig = 1'b0;
	#2 arst_sig = 1'b1;

	#40 rst_sig = 1'b1;
	#40 rst_sig = 1'b0; 

end
initial begin

	#100 $stop();
end
endmodule