// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Mon Sep 16 12:21:58 2019
`timescale 1 ps / 1 ps
 
module test;

reg clk_sig;
reg we_sig;
reg [4:0] adr_sig;
reg [31:0] data_sig;
reg [4:0] readadr_a_sig;
reg [4:0] readadr_b_sig;
reg arstn_sig;
wire [31:0] B;
wire [31:0] A;


LABA_2 LABA_2_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.we(we_sig) ,	// input  we_sig
	.adr(adr_sig) ,	// input [4:0] adr_sig
	.data(data_sig) ,	// input [31:0] data_sig
	.readadr_a(readadr_a_sig) ,	// input [4:0] readadr_a_sig
	.readadr_b(readadr_b_sig) ,	// input [4:0] readadr_b_sig
	.arstn(arstn_sig) ,	// input  arstn_sig
	.B(B_sig) ,	// output [31:0] B_sig
	.A(A_sig) 	// output [31:0] A_sig
);

         
initial begin 	
clk_sig=1'b0;		
forever #1 clk_sig =~ clk_sig;

end

initial begin
we_sig=1'b0;
adr_sig=5'b00000;
readadr_b_sig=5'b00000;
readadr_a_sig=5'b00000;
data_sig=32'hbad73;
#16 we_sig=1'b1;

	repeat(31) begin  
		#8 data_sig=data_sig+1;
		readadr_a_sig = readadr_a_sig + 1;
		readadr_b_sig = readadr_b_sig + 1;
		adr_sig=adr_sig+1;
				
	end
end

initial begin
 arstn_sig=1'b1;
#2 arstn_sig=1'b0;
#2 arstn_sig=1'b1;
				
end

initial begin
#600 $stop();
end

 endmodule

