
// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Mon Sep 30 20:07:56 2019
`timescale 1ns/1ps
module add_tb;
localparam WIDTH = 32;

reg [WIDTH-1:0] in_A_sig;
reg [WIDTH-1:0] in_B_sig;
reg in_opt_sig;

wire [WIDTH-1:0] out_sig;
wire ovrfl_sig;


add_sub add_sub_inst
(
	.in_A(in_A_sig) ,	// input [WIDTH-1:0] in_A_sig
	.in_B(in_B_sig) ,	// input [WIDTH-1:0] in_B_sig
	.in_opt(in_opt_sig) ,	// input  in_opt_sig
	.out(out_sig) ,	// output [WIDTH-1:0] out_sig
	.ovrfl(ovrfl_sig) 	// output  ovrfl_sig
);
initial begin
  in_A_sig = 32'h22222222;
  in_B_sig = 32'h11111111;
end

initial begin
  #10 in_opt_sig = 1'b0;
  #10 in_opt_sig = 1'b1;
end

initial begin 
  #400 $stop();
end
endmodule

