
// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Tue Oct  1 06:35:09 2019
`timescale 1ns/1ps

module alu_tb;

 reg [31:0]A_sig;
 reg [31:0]B_sig;
 reg [7:0]operation_sig;
 wire zf_sig;
 wire [31:0]resault_sig;
 wire of_sig;

integer i ;

ALU ALU_inst
(
	.A(A_sig) ,	// input [WIDTH-1:0] A_sig
	.B(B_sig) ,	// input [WIDTH-1:0] B_sig
	.operation(operation_sig) ,	// input [7:0] operation_sig
	.zf(zf_sig) ,	// output  zf_sig
	.resault(resault_sig) ,	// output [WIDTH-1:0] resault_sig
	.of(of_sig) 	// output  of_sig
);

defparam ALU_inst.WIDTH = 32;  

initial begin //add and sub module
A_sig = 32'h5645aa6c;
B_sig = 32'h12345101;
operation_sig = 8'b10111001;
#10 operation_sig = 8'b10111000;
end

initial begin //SHIFT module
#20 for( i = 0; i <= 7 ; i++)begin  
#10 operation_sig = {5'b00000,3'(i)};

end

end

initial begin //logick module
#110  A_sig = 32'b1;
B_sig = 32'b0;

end

initial begin
# 110 for(i=-1 ;i <= 3;i++)begin
# 10 operation_sig = {3'b110,2'(i),3'b000};

end

end

initial begin //mul and div module
# 200 A_sig = 32'h00000006;
B_sig = 32'h00000002;
end 

initial begin
# 200 operation_sig = 8'b10011100;
# 10 operation_sig = 8'b10011101;
# 10 operation_sig = 8'b10011010;
# 10 operation_sig = 8'b10011011;
end

initial begin

end

initial begin 
  #500 $stop();
end

endmodule



