// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Tue Sep 10 18:48:04 2019

lab1_using_toolchain lab1_using_toolchain_inst
(
	.data(data_sig) ,	// input [31:0] data_sig
	.arstn(arstn_sig) ,	// input  arstn_sig
	.srstn(srstn_sig) ,	// input  srstn_sig
	.clk(clk_sig) ,	// input  clk_sig
	.we(we_sig) ,	// input  we_sig
	.q(q_sig) 	// output [31:0] q_sig
);

