// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Tue Oct  1 16:29:25 2019
`timescale 1ns/1ps

module test;

reg [2:0] key_sig;
reg [4:0] shift_amount_sig;
reg [31:0] i_data_sig;
wire [31:0] result_sig;


barrel_shifter barrel_shifter_inst
(
	.key(key_sig),			// input [2:0] key_sig
	.shift_amount(shift_amount_sig),// input [4:0] shift_amount_sig
	.i_data(i_data_sig),		// input [31:0] i_data_sig
	.result(result_sig) 		// output [31:0] result_sig
);

initial begin 
	i_data_sig= 32'habcdabcd;
	key_sig = 3'b000;
	shift_amount_sig = 5'h4;

	#10 key_sig = 3'b000;	 //create by Vadim Kharchuk
	#10 key_sig = 3'b001;
	#10 key_sig = 3'b010;
	#10 key_sig = 3'b011;
	#10 key_sig = 3'b100;
	
end

initial begin
	#100 $stop();
end


endmodule
