// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Mon Oct 14 13:01:48 2019

`timescale 1ns/1ps
module Block1_inst;
localparam WIDTH = 32;

reg [WIDTH-1:0] in_A_sig; //code part take from Vadim Kharcuk
reg [WIDTH-1:0] in_B_sig;
reg [1:0] in_func_sig;
reg [2:0] in_opt_sig;

wire [WIDTH-1:0] result_sig;
wire zero_sig,ovrflow_sig;

Block1 Block1_inst
(
	.in_A(in_A_sig) ,	// input [WIDTH-1:0] in_a_sig
	.in_B(in_B_sig) ,	// input [WIDTH-1:0] in_b_sig
	.in_func(in_func_sig) ,	// input [1:0] in_func_sig
	.in_opt(in_opt_sig) ,	// input [2:0] in_opt_sig
	.result(result_sig) ,	// output [WIDTH-1:0] out_result_sig
	.zero(zero_sig) ,	// output  out_zero_sig
	.ovrflow(ovrflow_sig) 	// output  out_ovrfl_sig
);

initial begin
	in_A_sig = 32'h22222222;//add
	#20 in_A_sig = 32'd4; //mult
	#40 in_A_sig = 32'h12345678; //shift
	#50 in_A_sig = 32'h44444444; //logic
end
initial begin
	in_B_sig = 32'h11111111;//add
	#20 in_B_sig = 32'd2; //mult
	#40 in_B_sig = 5'h4; //shift
	#50 in_B_sig = 32'h44444444; //logic
end
initial begin
	in_func_sig = 2'b11;	//ADD
	#20 in_func_sig = 2'b00;	//MULT
	#40 in_func_sig = 2'b10; //SHIFT
	#50 in_func_sig = 2'b01; //LOGIC
end
initial begin
	in_opt_sig = 1'b0;		//ADD SUB TEST
	#10 in_opt_sig = 1'b1;

	#10 in_opt_sig = 2'b00;		//MULT HIGHT
	#10 in_opt_sig = 2'b10;		//MULT LOW
	#10 in_opt_sig = 2'b01;		//DIV HIGHT
	#10 in_opt_sig = 2'b11;

	#10 in_opt_sig = 3'b000;	//Sll
	#10 in_opt_sig = 3'b001;	//SRl
	#10 in_opt_sig = 3'b010;	//ROL
	#10 in_opt_sig = 3'b011;	//ROR
	#10 in_opt_sig = 3'b111;	//SRA

	#10 in_opt_sig = 2'b00; // &
	#10 in_opt_sig = 2'b01; // |
	#10 in_opt_sig = 2'b10; // ~( | )
	#10 in_opt_sig = 2'b11; // ^
	
end

initial begin 
	#400 $stop();
end
endmodule
